# Generated by Django 3.2.3 on 2021-12-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Course Code'),
        ),
    ]
