# Generated by Django 3.2.3 on 2021-12-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('courses', '0003_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Lecture Hall Name')),
            ],
        ),
        migrations.CreateModel(
            name='BookLectureHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('student_id', models.CharField(max_length=15, verbose_name='Student ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('complete', models.BooleanField(default=False, verbose_name='Confirm')),
                ('class_rooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courseRep.classrooms')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
