# Generated by Django 3.2.3 on 2021-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklecturehall',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='booklecturehall',
            name='student_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Student ID'),
        ),
    ]
