# Generated by Django 3.2.3 on 2021-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRep', '0003_auto_20211217_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklecturehall',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
